version: "3.9"
services:
#  web:
#    build: .
#    ports:
#      - "8000:5000"
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql-eh/data

volumes:
  db:
    driver: local